web/router.ex
defmodule Chatbox.Router do
  use Chatbox.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession # look in session for token
    plug Guardian.Plug.EnsureAuthenticated, handler: Chatbox.SessionController
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader # look in authorization header for token
    plug Guardian.Plug.LoadResource
  end

  scope "/", Chatbox do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete, :index]
  end

  scope "/", Chatbox do
    pipe_through [:browser, :browser_session]

    get "/chat", ChatController, :index
    resources "/users", UserController, only: [:show, :index, :update, :edit, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Chatbox do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Chatbox.LayoutView do
  use Chatbox.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Chatbox - The Application">
    <meta name="author" content="Eric Andre">

    <title>Hello Chatbox!</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <%= if Guardian.Plug.current_token(@conn) do %>
      <meta name="guardian_token" content="<%= Guardian.Plug.current_token(@conn) %>">
    <% end %>
  </head>

  <body>
    <div class="container">
      <header id="masthead" class="header" role="banner">
        <%= render "navigation.html", conn: @conn %>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

      <%= render "aside.html" %>

    </div> <!-- /container -->
    <%= render "footer.html"%>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/aside.html.eex
<aside role="complementary" id="sidebar">

</aside>

web/templates/layout/footer.html.eex
<footer role="contentinfo">
  <p class="container">Chatbox &copy; <span class="date">2016</span></p>
</footer>

web/templates/layout/navigation.html.eex
<nav role="navigation">
  <ul role="menu" class="nav nav-pills pull-right">
    <li role="menuitem">
      <a href="http://www.phoenixframework.org/docs">Get Started</a>
    </li>
    <li role="menuitem">
      <%= link "Chat", to: chat_path(@conn, :index)  %>
    </li>
    <li role="menuitem">
      <%= if logged_in?(@conn) do %>
        <%= link "Sign out", to: session_path(@conn, :delete, :access),  
          method: :delete, class: "btn btn-danger" %>
      <% else %>
        <%= link "Sign In", to: session_path(@conn, :new), class: "btn btn-primary" %>
      <% end %>
    </li>
  </ul>
</nav>