web/router.ex
defmodule Chatbox.Router do
  use Chatbox.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession # look in session for token
    plug Guardian.Plug.EnsureAuthenticated, handler: Chatbox.SessionController
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader # look in authorization header for token
    plug Guardian.Plug.LoadResource
  end

  scope "/", Chatbox do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete, :index]
  end

  scope "/", Chatbox do
    pipe_through [:browser, :browser_session]

    get "/chat", ChatController, :index
    resources "/users", UserController, only: [:show, :index, :update, :edit, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Chatbox do
  #   pipe_through :api
  # end
end

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Chatbox!" %></h2>
  <p>Are you ready to chat off?!?</p>
  <ul>
    <li><%= link "Sign Up", to: user_path(@conn, :new) %></li>
  </ul>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>